name: Setup Environment
description: Setup Environment

runs:
  using: "composite"
  steps:
    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v9

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: poetry install

    - name: Install fonts
      run: |
        apt install fonts-noto-color-emoji
        mkdir /usr/share/fonts/myfonts
        cp resources/fonts/* /usr/share/fonts/myfonts/
        fc-cache -fv
