name: MemeBot

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: false

jobs:
  meme-bot:
    if: startsWith(github.event.comment.body, '/')
    runs-on: ubuntu-latest
    name: Run MemeBot
    steps:
      - name: Generate Tags
        uses: docker/metadata-action@v4
        id: metadata
        with:
          images: ghcr.io/meetwq/github-meme-bot
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: MemeBot
        uses: docker://${{ steps.metadata.outputs.tags[0] }}
        env:
          APP_ID: ${{ secrets.MEME_APP_ID }}
          PRIVATE_KEY: ${{ secrets.MEME_PRIVATE_KEY }}
          SMMS_SECRET_TOKEN: ${{ secrets.SMMS_SECRET_TOKEN }}
